let inputlarghezza = prompt("scrivi larghezza in metri della stanza espressa in numeri decimali: ")
let inputlunghezza = prompt("scrivi lunghezza in metri della stanza espressa in numeri decimali: ")
let larghezza = parseFloat(inputlarghezza)
let lunghezza = parseFloat(inputlunghezza)
let area = (larghezza)*(lunghezza)
console.log(area, " m²")
